#spring:
#  datasource:
#    url:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username:
#    password:
#
#  # JPA settings
#  jpa :
#    database-platform : org.hibernate.dialect.MySQL57Dialect
#    show-sql : true
#    hibernate:
#      ddl-auto: update
